# Generated by Django 5.1.4 on 2025-01-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customerEmail",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("noOfDays", models.PositiveIntegerField()),
                ("chargeperDay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activityStatus", models.IntegerField(default=0)),
                (
                    "tokenNumber",
                    models.CharField(
                        blank=True, editable=False, max_length=4, unique=True
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "responseAlert",
                    models.CharField(
                        choices=[("emergency", "Emergency"), ("none", "None")],
                        default="none",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("reviewID", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField()),
                (
                    "emotion",
                    models.CharField(default="neutral", max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customerEmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("statusID", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "deliveryStatus",
                    models.CharField(
                        choices=[("delivered", "Delivered"), ("failed", "Failed")],
                        max_length=50,
                    ),
                ),
                ("isValid", models.BooleanField(default=True)),
                (
                    "customerEmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.customer",
                    ),
                ),
            ],
        ),
    ]
