# Generated by Django 5.0.3 on 2024-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negative_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Positive_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='data_created',
        ),
    ]
