# Generated by Django 5.1.4 on 2024-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_rename_review_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
