# Generated by Django 5.1.4 on 2025-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_staffprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="staff_profiles/"),
        ),
    ]
