# Generated by Django 5.1.4 on 2024-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="id",
        ),
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
        migrations.AlterField(
            model_name="reviews",
            name="phone_number",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_name",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
