# Generated by Django 5.1.4 on 2025-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_staffprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
