# Generated by Django 5.1.4 on 2024-12-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_remove_reviews_id_remove_users_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="note",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
