# Generated by Django 5.1.4 on 2025-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_customer_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="verification_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
