# Generated by Django 5.1.4 on 2024-12-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_reviews_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="note",
        ),
    ]
