# Generated by Django 5.1.4 on 2025-02-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_customer_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="tokenNumber",
            field=models.CharField(
                blank=True, editable=False, max_length=10, unique=True
            ),
        ),
    ]
