# Generated by Django 5.1.4 on 2024-12-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_remove_reviews_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
