# Generated by Django 5.1.4 on 2024-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0008_delete_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="emotion",
            field=models.CharField(default="neutral", max_length=50, null=True),
        ),
    ]
