# Generated by Django 5.1.4 on 2025-02-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0008_alter_customer_tokennumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="tokenNumber",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=10, unique=True
            ),
        ),
    ]
