# Generated by Django 5.1.4 on 2025-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0009_alter_customer_tokennumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="customerEmail",
        ),
        migrations.AddField(
            model_name="reviews",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
