# Generated by Django 5.1.4 on 2025-02-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0010_remove_reviews_customeremail_reviews_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Accounts.customer"
            ),
        ),
    ]
