# Generated by Django 5.1.4 on 2025-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0011_alter_reviews_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
