# Generated by Django 5.1.4 on 2025-03-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0013_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="responseAlert",
        ),
        migrations.AddField(
            model_name="reviews",
            name="responseAlert",
            field=models.CharField(
                choices=[("emergency", "Emergency"), ("none", "None")],
                default="none",
                max_length=50,
            ),
        ),
    ]
