# Generated by Django 5.1.4 on 2025-03-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0014_remove_customer_responsealert_reviews_responsealert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="responseAlert",
            field=models.BooleanField(default=False),
        ),
    ]
