# Generated by Django 5.1.4 on 2025-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0015_alter_reviews_responsealert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="chargeperDay",
        ),
        migrations.AddField(
            model_name="customer",
            name="charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="roomType",
            field=models.CharField(
                choices=[
                    ("single", "Single Room"),
                    ("deluxe", "Deluxe Room"),
                    ("double", "Double Room"),
                ],
                default="double",
                max_length=50,
            ),
        ),
    ]
